//File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCd2FvXHgYLREcbkboLi-5NqsCeZfy3OA',
    appId: '1:453564223452:web:9b08426ff426893a39c919',
    messagingSenderId: '453564223452',
    projectId: 'leaflife-bda2f',
    authDomain: 'leaflife-bda2f.firebaseapp.com',
    storageBucket: 'leaflife-bda2f.appspot.com',
    measurementId: 'G-RTV2ST8N1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC91zgZdVghMoPbIBL6_68AqFNlXqWs9nM',
    appId: '1:453564223452:android:1071aa0a12a46ef539c919',
    messagingSenderId: '453564223452',
    projectId: 'leaflife-bda2f',
    storageBucket: 'leaflife-bda2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1XOcmYUM2XarJTvBXZolYeVnqzoRa3KE',
    appId: '1:453564223452:ios:cc3b95425ad22e7539c919',
    messagingSenderId: '453564223452',
    projectId: 'leaflife-bda2f',
    storageBucket: 'leaflife-bda2f.appspot.com',
    iosBundleId: 'com.example.nutritionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1XOcmYUM2XarJTvBXZolYeVnqzoRa3KE',
    appId: '1:453564223452:ios:8777081f5d62a49739c919',
    messagingSenderId: '453564223452',
    projectId: 'leaflife-bda2f',
    storageBucket: 'leaflife-bda2f.appspot.com',
    iosBundleId: 'com.example.nutritionapp.RunnerTests',
  );
}
